### ISSUE TITLE
关于characteristic_valueChanged中的一个小错误指明

### ISSUE THREAD

**Issue by aitankey** [miuser00/BLEComm#1]
对于indicate和notify通知里面，在收到flag改变后，invoke里面虽然定义了一个 var result=args.CharacteristicValue 但是在下面显示到UI界面上的时候都是ble_result，应该是复制粘贴过来没有修改过来？应该把result的值赋给data。很感谢分享，对于新手学习BLE受益匪浅！

**Comment by miuser00** [comment]
Thanks a lot,corrected
